Feature/issue 024
Nexters-PIMO/PIMO_Android pull request #35
Opened 2023-02-19 10:42 UTC by pjs5221

### 이슈
- resolved: #24 

### 내용
- 온보딩 화면 구현
- 로그인 화면 구현

2023-02-20 03:23 UTC, yjyoon-dev commented on domain/src/main/java/com/nexters/pimo/domain/usecase/LoginUseCase.kt
> +import com.nexters.pimo.domain.repository.UserRepository
이 파일들은 없는 파일이라 컴파일이 안되네. 추가하던지 import를 빼줘야 할 것 같아.

2023-02-20 03:33 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            )
텍스트 색상이 Figma랑 다른 것 같은데 다시 확인해줘

2023-02-20 03:34 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            .paint(painterResource(id = R.drawable.bg_login), contentScale = ContentScale.FillHeight)
<img width="40%" src="https://user-images.githubusercontent.com/72238126/220003497-875407a2-f87d-478c-bc03-59694457595d.png"/>

`FillHeight` 로 맞추면 위 사진처럼 기기에 따라서 좌우 여백이 빌 수 있어.

2023-02-20 03:36 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +                contentDescription = null,
이미지 해상도를 너무 낮게 뽑아서 기기에서 어색하게 보여.
Figma에서 export 할 때 `2~4x` 배율 해상도로 추출해서 써줘.

2023-02-20 03:44 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +                    3 -> Onboard4(onClick = onSkip)
모든 페이지가 다 똑같이 생기고 제목이랑 부제목만 바뀌는데,
똑같은 코드를 갖는 `Onboard`를 4개씩 만드는건 코드 중복이 너무 큰 것 같아.
```kotlin
data class OnboardingStep(
    val step: Int,
    @StringRes val titleRes: Int,
    @StringRes val subtitleRes: Int
)

@Composable
fun OnboardContent(
    step: OnboardingStep,
    onSkip: () -> Unit
) {
    Text(text = stringResource(id = step.titleRes))
    // . . .
}
```
이런 식으로 할 수 있을 것 같아

2023-02-20 03:46 UTC, yjyoon-dev commented on presentation/src/main/res/values/strings.xml
> +    <string name="onboard_content_2">피모에는 글이 있는 글사진만 업로드할 수 있어요. 우리가 똑똑하게 인식한 글사진 속 텍스트를 버튼 하나로 자유롭게 복사, 공유해보세요.</string>
content 텍스트 말고 title 텍스트는 너비가 넘어갈 일이 없어보여서
figma 디자인이랑 똑같이 줄바꿈 넣어줘도 될 것 같아.

2023-02-20 03:51 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginState.kt
> +    val result: LoginResult? = null,
state에서 `null` 값은 최대한 사용하지 않는 게 좋아.
`LoginResult.Unspecified` 같은 초기 상태를 하나 추가해줘.

2023-02-20 03:52 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginViewModel.kt
> +            .getOrNull()
null 값이 들어갈 수 있으니 `getOrNull()` 대신 `getOrThrow()`

2023-02-20 03:53 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +        exit = fadeOut(),
`visible = true` 면 항상 보이는거라 아무런 애니메이션 효과가 없는데 왜 넣은거야?

2023-02-20 03:55 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +    }
`lastPage`를 따로 확인하는 이유가 있어?

2023-02-20 04:00 UTC, yjyoon-dev commented on domain/src/main/java/com/nexters/pimo/domain/model/LoginResult.kt
> +    object SignedFirst : LoginResult
주석을 빼주고 필드 이름을 이해할 수 있도록 충분히 구체적으로 써줘.
그리고 로그인을 완료했으면 그에 따른 유저 데이터도 결과로 들어가야 할 것 같아.
```kotlin
sealed interface LoginResult {
    data class SignedIn(user: User) : LoginResult
    object NotSignedUpYet : LoginResult
}

2023-02-20 04:03 UTC, yjyoon-dev commented
PR 제목이 기본으로 되어 있는데 기능 구현에 맞게 수정해줘!

2023-02-20 04:03 UTC, yjyoon-dev requested changes
PR 제목이 기본으로 되어 있는데 기능 구현에 맞게 수정해줘!

2023-02-20 13:12 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +        exit = fadeOut(),
visible 항목은 필수값으로 들어가야 되던데, 그래서 true로 넣었어

2023-02-20 13:25 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +        exit = fadeOut(),
필드말고 `AnimatedVisibility` 를 쓴 이유가 궁금했어.

2023-02-20 13:39 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            .paint(painterResource(id = R.drawable.bg_login), contentScale = ContentScale.FillHeight)
FillBounds 로 써야되나??

2023-02-20 14:42 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            .paint(painterResource(id = R.drawable.bg_login), contentScale = ContentScale.FillHeight)
FillBounds도 잘 나오는거같네~

2023-02-20 14:44 UTC, yjyoon-dev requested changes
<img width="40%" src="https://user-images.githubusercontent.com/72238126/220136923-33f948b0-90f4-4691-8941-0482750b95fe.png"/>

온보딩 첫번째 화면에 있는 fimo 로고 사진 해상도 아직 안바뀌었어~

2023-02-21 00:08 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            )
수정완료

2023-02-21 00:09 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +            .paint(painterResource(id = R.drawable.bg_login), contentScale = ContentScale.FillHeight)
수정완료

2023-02-21 00:09 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +                    3 -> Onboard4(onClick = onSkip)
수정완료

2023-02-21 00:09 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginState.kt
> +    val result: LoginResult? = null,
수정완료

2023-02-21 00:09 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginViewModel.kt
> +            .getOrNull()
수정완료

2023-02-21 00:09 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +        exit = fadeOut(),
AnimatedVisibility  삭제완료

2023-02-21 00:09 UTC, pjs5221 commented on domain/src/main/java/com/nexters/pimo/domain/model/LoginResult.kt
> +    object SignedFirst : LoginResult
수정완료

2023-02-21 00:10 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/onboard/OnboardScreen.kt
> +    }
삭제완료

2023-02-21 00:11 UTC, pjs5221 commented on presentation/src/main/res/values/strings.xml
> +    <string name="onboard_content_2">피모에는 글이 있는 글사진만 업로드할 수 있어요. 우리가 똑똑하게 인식한 글사진 속 텍스트를 버튼 하나로 자유롭게 복사, 공유해보세요.</string>
수정완료

2023-02-21 00:11 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/login/LoginScreen.kt
> +                contentDescription = null,
수정완료

2023-02-21 00:13 UTC, pjs5221 commented
온보딩 첫번째 화면에 있는 fimo 로고 해상도 1x -> 2x로 바꾼건데 더 높여야되나..

2023-02-21 11:09 UTC, pjs5221 commented
수정했어~

2023-02-21 11:51 UTC, yjyoon-dev approved these changes
LGTM👍

2023-02-21 11:51 UTC, merged