프로필 생성 화면 구현
Nexters-PIMO/PIMO_Android pull request #39
Opened 2023-02-22 16:56 UTC by pjs5221

### 이슈
- resolved: #25 

### 내용
- 프로필 생성 화면 구현

2023-02-23 09:46 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/profile/ProfileTopBar.kt
> +        ) {
불필요한 괄호는 없애줘

2023-02-23 09:49 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/profile/ProfileViewModel.kt
> +        //중복 체크
중복체크 말고 유효성 체크는 클라이언트에서 구현해야 하는거라 이건 구현해서 다시 올려줘

2023-02-23 09:58 UTC, yjyoon-dev requested changes
### 그 외 수정사항
1. TopAppBar의 뒤로가기 버튼 사이즈가 Figma에 비해 너무 커
2. 아카이브 생성 완료 화면 좌우 여백이 Figma에 비해 너무 좁아

수고 많았어~ 조금만 수정 부탁할게!!👍

2023-02-23 13:03 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/profile/ProfileTopBar.kt
> +        ) {
수정완료

2023-02-23 14:24 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/profile/ProfileViewModel.kt
> +        //중복 체크
수정완료

2023-02-23 14:26 UTC, pjs5221 commented
> ### 그 외 수정사항
> 1. TopAppBar의 뒤로가기 버튼 사이즈가 Figma에 비해 너무 커
> 2. 아카이브 생성 완료 화면 좌우 여백이 Figma에 비해 너무 좁아
> 
> 수고 많았어~ 조금만 수정 부탁할게!!👍


---> 아카이브 생성 완료 화면 좌우 여백은 Figma처럼 20dp로 맞춘건뎅

2023-02-23 15:36 UTC, yjyoon-dev requested changes
아 아카이브 생성 완료 화면은 내가 ios 화면 보고 말했었네.
우선은 그대로 두고 나중에 디자이너한테 ios android 여백 다른거 물어봐야겠다.

그리고 한 가지 버그가 있는데,
중복확인 하고나서 `TextField` 값이 바뀌면 validation을 초기화 시켜줘야해.
예를 들어서 정상적인 닉네임을 치고 중복확인 한 뒤에 다시 특수문자를 치면
계속하기 버튼이 그대로 활성화 되어있어서 이상한 닉네임으로 진행할 수 있게 되네.
이거 수정해줘.

2023-02-25 06:02 UTC, yjyoon-dev approved these changes
LGTM👍

2023-02-25 07:26 UTC, merged