설정 화면 구현
Nexters-PIMO/PIMO_Android pull request #44
Opened 2023-03-02 13:41 UTC by pjs5221

### 이슈
- resolved: #29 

### 내용
- 설정 화면 구현

2023-03-02 14:03 UTC, yjyoon-dev requested changes
`develop` 브랜치랑 merge 충돌 해결을 안하고 올려줬네...
해결하고 다시 올려줘~

2023-03-07 00:48 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/settings/SettingsScreen.kt
> +            backIconRes = R.drawable.ic_back,
뒤로가기 아이콘이 조금 작은 것 같아.
`FimoSimpleAppBar`에 `backIconSize = 16.dp` 로 사이즈 값도 전달해줘!

2023-03-07 00:52 UTC, yjyoon-dev commented on presentation/src/main/java/com/nexters/pimo/ui/main/MainScreen.kt
> +                        startSettingsActivity = startSettingsActivity
HomeScreen 처럼 FeedScreen 에도 SettingActivity 연결해줘!

2023-03-07 00:54 UTC, yjyoon-dev requested changes
고생했어~ 사소한 것들이지만 마저 수정 부탁할게!

2023-03-08 14:42 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/main/MainScreen.kt
> +                        startSettingsActivity = startSettingsActivity
ok

2023-03-08 14:42 UTC, pjs5221 commented on presentation/src/main/java/com/nexters/pimo/ui/settings/SettingsScreen.kt
> +            backIconRes = R.drawable.ic_back,
ok

2023-03-09 07:18 UTC, merged